# Generated by Django 4.2.7 on 2023-11-30 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp3', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='image',
            new_name='img',
        ),
    ]
